### ISSUE TITLE
Website Content

### ISSUE THREAD

**Issue by Corb3nik** [CFI-UL/cfi-ul.github.io#1]
Here is a list of what would be appropriate to see in the website for now : 

- [x] Organization description (about us)
- [x] Hall of fame (past competitions with positions)
- [x] Upcoming events
- [x] Contact Information
- [ ] Google calendar integration

To be discussed : 
- [x] Sponsor page

**Comment by masterT** [comment]
Google calendar integration will be discussed here https://github.com/CFI-UL/cfi-ul.github.io/issues/12. Everything else is done!
