### ISSUE TITLE
Hall of Fame events date?

### ISSUE THREAD

**Issue by masterT** [CFI-UL/cfi-ul.github.io#2]
Should we had the date for the event of the Hall of Fame?

**Comment by Corb3nik** [comment]
I think the year is enough. If they really want the dates, they'll check it out for themselves.

**Comment by masterT** [comment]
Ok, I may have fucked up the chronological order then, but only the year matters so it's ok right?

**Comment by Corb3nik** [comment]
I'd try to keep them in chronological order as much as possible, but its not a big deal if it isn't.

**Comment by masterT** [comment]
Ok, I will store the events in a data file `hall-of-fame\.(json|yaml|.+)` with the date, and generate the hall of fame section from it. It will include the date, but I won't be displayed.

**Comment by masterT** [comment]
Fuck date, only year matters.
